export const FakeData = {
  "d-1": {
    "thumbnail":
      "https://upload.wikimedia.org/wikipedia/pt/7/7b/Graduation_%28%C3%A1lbum_de_Kanye_West%29.jpg",
    "title": "Graduation",
    "subtitle": "Album • Kanye West",
    "owner": "kanye_west",
    "category": "album",
    "fixado": false,
    "tocando": false,
    "data": new Date(),
    "access": 0,
  },
  "d-2": {
    "thumbnail":
      "https://is1-ssl.mzstatic.com/image/thumb/Music124/v4/db/91/88/db918861-6232-a2d1-16f6-b92f8cb415dc/00602537993772.rgb.jpg/256x256bb.jpg",
    "title": "1989",
    "subtitle": "Album • Taylor Swift",
    "owner": "taylor_swift",
    "category": "album",
    "fixado": false,
    "tocando": false,
    "data": new Date(),
    "access": 0,
  },
  "d-3": {
    "thumbnail":
      "https://i.scdn.co/image/ab67616d000048518c8edbab9129346ddac409b5",
    "title": "Tim Maia",
    "subtitle": "Artista",
    "category": "artist",
    "owner": "tim_maia",
    "fixado": false,
    "tocando": false,
    "data": new Date(),
    "access": 0,
  },
  "d-4": {
    "thumbnail":
      "https://yt3.googleusercontent.com/ytc/AIdro_lcANyUGo52inuonLcVgXZ9hKOFyLs9OckqWagy4w=s900-c-k-c0x00ffffff-no-rj",
    "title": "Flow Podcast",
    "subtitle": "Podcast • Flow Podcast",
    "owner": "flow_podcast",
    "category":"podcast",
    "fixado": false,
    "tocando": false,
    "data": new Date(),
    "access": 0,
  },
  "d-5": {
    "thumbnail":
      "https://upload.wikimedia.org/wikipedia/pt/7/7b/Graduation_%28%C3%A1lbum_de_Kanye_West%29.jpg",
    "title": "Graduation",
    "subtitle": "Album • Kanye West",
    "owner": "kanye_west",
    "category": "album",
    "fixado": false,
    "tocando": false,
    "data": new Date(),
    "access": 0,
  },
  "d-6": {
    "thumbnail":
      "https://is1-ssl.mzstatic.com/image/thumb/Music124/v4/db/91/88/db918861-6232-a2d1-16f6-b92f8cb415dc/00602537993772.rgb.jpg/256x256bb.jpg",
    "title": "1989",
    "subtitle": "Album • Taylor Swift",
    "owner": "taylor_swift",
    "category": "album",
    "fixado": false,
    "tocando": false,
    "data": new Date(),
    "access": 0,
  },
  "d-7": {
    "thumbnail":
      "https://i.scdn.co/image/ab67616d000048518c8edbab9129346ddac409b5",
    "title": "Tim Maia",
    "subtitle": "Artista",
    "category": "artist",
    "owner": "tim_maia",
    "fixado": false,
    "tocando": false,
    "data": new Date(),
    "access": 0,
  },
  "d-8": {
    "thumbnail":
      "https://yt3.googleusercontent.com/ytc/AIdro_lcANyUGo52inuonLcVgXZ9hKOFyLs9OckqWagy4w=s900-c-k-c0x00ffffff-no-rj",
    "title": "Flow Podcast",
    "subtitle": "Podcast • Flow Podcast",
    "owner": "flow_podcast",
    "category":"podcast",
    "fixado": false,
    "tocando": false,
    "data": new Date(),
    "access": 0,
  },
  "d-9": {
    "thumbnail":
      "https://upload.wikimedia.org/wikipedia/pt/7/7b/Graduation_%28%C3%A1lbum_de_Kanye_West%29.jpg",
    "title": "Graduation",
    "subtitle": "Album • Kanye West",
    "owner": "kanye_west",
    "category": "album",
    "fixado": false,
    "tocando": false,
    "data": new Date(),
    "access": 0,
  },
  "d-10": {
    "thumbnail":
      "https://is1-ssl.mzstatic.com/image/thumb/Music124/v4/db/91/88/db918861-6232-a2d1-16f6-b92f8cb415dc/00602537993772.rgb.jpg/256x256bb.jpg",
    "title": "1989",
    "subtitle": "Album • Taylor Swift",
    "owner": "taylor_swift",
    "category": "album",
    "fixado": false,
    "tocando": false,
    "data": new Date(),
    "access": 0,
  },
  "d-11": {
    "thumbnail":
      "https://i.scdn.co/image/ab67616d000048518c8edbab9129346ddac409b5",
    "title": "Tim Maia",
    "subtitle": "Artista",
    "category": "artist",
    "owner": "tim_maia",
    "fixado": false,
    "tocando": false,
    "data": new Date(),
    "access": 0,
  },
  "d-12": {
    "thumbnail":
      "https://yt3.googleusercontent.com/ytc/AIdro_lcANyUGo52inuonLcVgXZ9hKOFyLs9OckqWagy4w=s900-c-k-c0x00ffffff-no-rj",
    "title": "Flow Podcast",
    "subtitle": "Podcast • Flow Podcast",
    "owner": "flow_podcast",
    "category":"podcast",
    "fixado": false,
    "tocando": false,
    "data": new Date(),
    "access": 0,
  },
  "d-13": {
    "thumbnail":
      "https://upload.wikimedia.org/wikipedia/pt/7/7b/Graduation_%28%C3%A1lbum_de_Kanye_West%29.jpg",
    "title": "Graduation",
    "subtitle": "Album • Kanye West",
    "owner": "kanye_west",
    "category": "album",
    "fixado": false,
    "tocando": false,
    "data": new Date(),
    "access": 0,
  },
  "d-14": {
    "thumbnail":
      "https://is1-ssl.mzstatic.com/image/thumb/Music124/v4/db/91/88/db918861-6232-a2d1-16f6-b92f8cb415dc/00602537993772.rgb.jpg/256x256bb.jpg",
    "title": "1989",
    "subtitle": "Album • Taylor Swift",
    "owner": "taylor_swift",
    "category": "album",
    "fixado": false,
    "tocando": false,
    "data": new Date(),
    "access": 0,
  },
  "d-15": {
    "thumbnail":
      "https://i.scdn.co/image/ab67616d000048518c8edbab9129346ddac409b5",
    "title": "Tim Maia",
    "subtitle": "Artista",
    "category": "artist",
    "owner": "tim_maia",
    "fixado": false,
    "tocando": false,
    "data": new Date(),
    "access": 0,
  },
  "d-16": {
    "thumbnail":
      "https://yt3.googleusercontent.com/ytc/AIdro_lcANyUGo52inuonLcVgXZ9hKOFyLs9OckqWagy4w=s900-c-k-c0x00ffffff-no-rj",
    "title": "Flow Podcast",
    "subtitle": "Podcast • Flow Podcast",
    "owner": "flow_podcast",
    "category":"podcast",
    "fixado": false,
    "tocando": false,
    "data": new Date(),
    "access": 0,
  }
}
